// <auto-generated />
using System;
using MAI.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace MAI.Migrations
{
    [DbContext(typeof(MAIDbContext))]
    partial class MAIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MAI.Models.Cidade", b =>
                {
                    b.Property<int>("IdCidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCidade"));

                    b.Property<string>("CidadeNome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("EstadoIdEstado")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdEstado")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdCidade");

                    b.HasIndex("EstadoIdEstado");

                    b.ToTable("TB_MAI_CIDADE");
                });

            modelBuilder.Entity("MAI.Models.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresa"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("IdLogin")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdRegiao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("LoginIdLogin")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("RegiaoIdRegiao")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdEmpresa");

                    b.HasIndex("LoginIdLogin");

                    b.HasIndex("RegiaoIdRegiao");

                    b.ToTable("TB_MAI_EMPRESA");
                });

            modelBuilder.Entity("MAI.Models.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("EstadoNome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)");

                    b.HasKey("IdEstado");

                    b.ToTable("TB_MAI_ESTADO");
                });

            modelBuilder.Entity("MAI.Models.Login", b =>
                {
                    b.Property<int>("IdLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLogin"));

                    b.Property<string>("EmailLogin")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Email");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdLogin");

                    b.ToTable("TB_MAI_LOGIN");
                });

            modelBuilder.Entity("MAI.Models.Regiao", b =>
                {
                    b.Property<int>("IdRegiao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRegiao"));

                    b.Property<int?>("CidadeIdCidade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdCidade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("RegiaoNome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdRegiao");

                    b.HasIndex("CidadeIdCidade");

                    b.ToTable("TB_MAI_REGIAO");
                });

            modelBuilder.Entity("MAI.Models.Cidade", b =>
                {
                    b.HasOne("MAI.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoIdEstado");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("MAI.Models.Empresa", b =>
                {
                    b.HasOne("MAI.Models.Login", "Login")
                        .WithMany()
                        .HasForeignKey("LoginIdLogin");

                    b.HasOne("MAI.Models.Regiao", "Regiao")
                        .WithMany()
                        .HasForeignKey("RegiaoIdRegiao");

                    b.Navigation("Login");

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("MAI.Models.Regiao", b =>
                {
                    b.HasOne("MAI.Models.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeIdCidade");

                    b.Navigation("Cidade");
                });
#pragma warning restore 612, 618
        }
    }
}
